name: Deploy to freecode.camp

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install universe CLI
        run: npm install -g @freecodecamp/universe-cli

      - name: Deploy
        run: universe static deploy --promote
        env:
          GITHUB_TOKEN: ${{ secrets.UNIVERSE_DEPLOY_TOKEN }}
